---
title: "SpaTalk"
output: html_document
date: "2025-02-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("/gpfs/gibbs/project/wang_zuoheng/xx244/GITIII_benchmark")
```

# Mouse brain

```{r}
Sys.setenv(RETICULATE_AUTOCONFIGURE = "FALSE")
Sys.setenv(RETICULATE_PYTHON = "/home/xx244/.conda/envs/benchmark/bin/python")
library(SpaTalk)
library(reticulate)
torch <- import("torch")

py_list <- torch$load("/gpfs/gibbs/project/wang_zuoheng/xx244/GITIII_benchmark/data/mouse/genes.pth")
vec <- unlist(py_list)
genes<-ifelse(grepl("^[0-9]", vec), paste0("X", vec), vec)
genes<-gsub("-", ".", genes)
```

```{r}
df<-read.csv("/gpfs/gibbs/project/wang_zuoheng/xx244/GITIII_benchmark/data/mouse/mouse.csv")
df<-df[df$slice_id=="mouse1_slice201",]
exp<-t(as.matrix(df[,genes]))
```

```{r}
metadata <- data.frame(
  cell = rownames(df),  # Extract row names
  x = df$centerx,       # Extract 'centerx' column
  y = df$centery        # Extract 'centery' column
)

obj <- createSpaTalk(st_data = exp,
                     st_meta = metadata,
                     species = "Mouse",
                     if_st_is_sc = T,
                     spot_max_cell = 1,
                     celltype = df$subclass)
```
```{r}
# Filter LRIs with downstream targets
obj <- find_lr_path(object = obj, lrpairs = lrpairs, pathways = pathways)
obj <- dec_cci_all(object = obj)
```

# AD


```{r}
py_list <- torch$load("/gpfs/gibbs/project/wang_zuoheng/xx244/GITIII_benchmark/data/AD/genes.pth")
vec <- unlist(py_list)
genes<-ifelse(grepl("^[0-9]", vec), paste0("X", vec), vec)
genes<-gsub("-", ".", genes)

df<-read.csv("/gpfs/gibbs/project/wang_zuoheng/xx244/GITIII_benchmark/data/AD/AD.csv")
df<-df[df$section=="H20.33.001.CX28.MTG.02.007.1.02.03",]
exp<-t(as.matrix(df[,genes]))

metadata <- data.frame(
  cell = rownames(df),  # Extract row names
  x = df$centerx,       # Extract 'centerx' column
  y = df$centery        # Extract 'centery' column
)

obj <- createSpaTalk(st_data = exp,
                     st_meta = metadata,
                     species = "Human",
                     if_st_is_sc = T,
                     spot_max_cell = 1,
                     celltype = df$subclass)
```
```{r}
# Filter LRIs with downstream targets
obj <- find_lr_path(object = obj, lrpairs = lrpairs, pathways = pathways)
obj <- dec_cci_all(object = obj)
```

# NSCLC


```{r}
py_list <- torch$load("/gpfs/gibbs/project/wang_zuoheng/xx244/GITIII_benchmark/data/NSCLC/genes.pth")
vec <- unlist(py_list)
genes<-ifelse(grepl("^[0-9]", vec), paste0("X", vec), vec)
genes<-gsub("-", ".", genes)

df<-read.csv("/gpfs/gibbs/project/wang_zuoheng/xx244/GITIII_benchmark/data/NSCLC/NSCLC.csv")
rownames(df) <- paste0("C", rownames(df))
df<-df[df$section=="Lung6",]
exp<-t(as.matrix(df[,genes]))

metadata <- data.frame(
  cell = rownames(df),  # Extract row names
  x = df$CenterX_global_px,       # Extract 'centerx' column
  y = df$CenterY_global_px        # Extract 'centery' column
)

obj <- createSpaTalk(st_data = exp,
                     st_meta = metadata,
                     species = "Human",
                     if_st_is_sc = T,
                     spot_max_cell = 1,
                     celltype = df$CellType)
```

```{r}
# Filter LRIs with downstream targets
obj <- find_lr_path(object = obj, lrpairs = lrpairs, pathways = pathways)
obj <- dec_cci_all(object = obj)
```

# BC


```{r}
py_list <- torch$load("/gpfs/gibbs/project/wang_zuoheng/xx244/GITIII_benchmark/data/BC/genes.pth")
vec <- unlist(py_list)
genes<-ifelse(grepl("^[0-9]", vec), paste0("X", vec), vec)
genes<-gsub("-", ".", genes)

df<-read.csv("/gpfs/gibbs/project/wang_zuoheng/xx244/GITIII_benchmark/data/BC/BC.csv")
rownames(df) <- paste0("C", rownames(df))
df<-df[df$section=="sample1_rep1",]
exp<-t(as.matrix(df[,genes]))

metadata <- data.frame(
  cell = rownames(df),  # Extract row names
  x = df$centerx,       # Extract 'centerx' column
  y = df$centery        # Extract 'centery' column
)

obj <- createSpaTalk(st_data = exp,
                     st_meta = metadata,
                     species = "Human",
                     if_st_is_sc = T,
                     spot_max_cell = 1,
                     celltype = df$subclass)
```

```{r}
# Filter LRIs with downstream targets
obj <- find_lr_path(object = obj, lrpairs = lrpairs, pathways = pathways)
obj <- dec_cci_all(object = obj)
```









